name: Build ZAuto VIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      PYTHON_VERSION: "3.10"
      JAVA_VERSION: "11"

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            zip unzip git \
            openjdk-11-jdk \
            autoconf automake libtool \
            pkg-config zlib1g-dev \
            libncurses5-dev \
            libffi-dev libssl-dev \
            ccache \
            libjpeg-dev \
            libpng-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip setuptools wheel

          pip install \
            Cython==0.29.33 \
            buildozer==1.4.0

      - name: Accept Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

      - name: Clean Old Build
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Build Debug APK
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZAuto_APK
          path: bin/*.apk
